# Generated by Django 4.1.6 on 2023-02-10 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.AddField(
            model_name='movie',
            name='screen',
            field=models.CharField(default='Screen 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='show_times',
            field=models.TimeField(default=datetime.datetime(2023, 1, 1, 20, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
